### ISSUE TITLE
Change alias

### ISSUE THREAD

**Issue by Merisho** [ilopX/yii2-basic-htaccess#1]
Hi
I have a problem with my @web alias. It always change, when I'm not in root:
mysite — here alias is good
mysite/product?name=item — alias=/product?name=item

**Comment by ilopX** [comment]
Hi
I'm not sure I understand your question
my web alias always \yii::getAlias('@web') == ''

**Comment by Merisho** [comment]
I will deal with it soon maybe.
However, I can use a root path "/" instead of @web, I think it's the same
