### ISSUE TITLE
Yii2 url fomatting

### ISSUE THREAD

**Issue by gitaitechnologies** [ilopX/yii2-basic-htaccess#4]
Hi there,

Thanks for the tute. Its amazing. I saw video as well and followed the same procedure. Everything works fine and for about I got url http://localhost/yiibasic/web/about. Now to remove "web" from url I write 
'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'dfjdjhgfdj2343jdfhg',
            'baseUrl' => '',
        ],
Following which yii throws error 404. Pls guide where am I doing mistake.

**Comment by kishor10d** [comment]
Hello there, 
Thanks for the .htaccess. I followed all your procedure but the same problem of 404 occurred when I un-comment the 'baseUrl'.
It works when I hit "http://localhost/yiibasic/web/about".

The same problem which @gitaitechnologies mentioned.

Do you have any solution?
